[package]
name = "tree-sitter-tony"
version = "0.1.0"
description = "Tree-sitter grammar for Tony language"
authors = []
edition = "2021"

[lib]
path = "binding.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
tree-sitter = ">= 0.20"

[build-dependencies]
cc = "1.0"
